# Generated by Django 2.2.3 on 2019-07-29 23:31

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('ps_app', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Paries',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('equipeA', models.CharField(max_length=100, null=True)),
                ('score', models.CharField(max_length=100, null=True)),
                ('equipeB', models.CharField(max_length=100, null=True)),
                ('montant_parié', models.CharField(max_length=100, null=True)),
                ('id_user', models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, related_name='user_parie', to='Nams.User')),
            ],
        ),
    ]
