# Generated by Django 2.2.3 on 2019-07-29 23:35

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('ps_app', '0002_paries'),
    ]

    operations = [
        migrations.AddField(
            model_name='paries',
            name='date_parie',
            field=models.DateTimeField(auto_now_add=True, null=True),
        ),
    ]
