# Generated by Django 2.2.3 on 2019-07-29 23:51

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('ps_app', '0003_paries_date_parie'),
    ]

    operations = [
        migrations.AddField(
            model_name='paries',
            name='scoreB',
            field=models.CharField(max_length=100, null=True),
        ),
    ]
