# Generated by Django 2.2.3 on 2019-07-30 13:01

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('ps_app', '0004_paries_scoreb'),
    ]

    operations = [
        migrations.AddField(
            model_name='paries',
            name='date_match',
            field=models.DateField(null=True),
        ),
        migrations.AlterField(
            model_name='paries',
            name='equipeA',
            field=models.CharField(max_length=100, null=True, unique=True),
        ),
        migrations.AlterField(
            model_name='paries',
            name='equipeB',
            field=models.CharField(max_length=100, null=True, unique=True),
        ),
        migrations.AlterField(
            model_name='paries',
            name='score',
            field=models.CharField(max_length=100, null=True, verbose_name='scoreA'),
        ),
    ]
