# Generated by Django 2.2.3 on 2019-07-30 14:12

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('ps_app', '0005_auto_20190730_1301'),
    ]

    operations = [
        migrations.AddField(
            model_name='paries',
            name='v_date_match',
            field=models.CharField(max_length=100, null=True),
        ),
    ]
